### ISSUE TITLE
Lot numbers not being parsed from PDF

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/the_rural_city_of_murray_bridge_sa_development_applications#1]
The PDFs do seem to have lot numbers, but these aren't being imported into the database

For instance, looking at http://www.murraybridge.sa.gov.au/webdata/resources/files/November%202018%20Development%20Decisions.pdf, the first application is "LOT: 10"

**Comment by jamezpolley** [comment]
Once this is closed we can activate this authority.

**Comment by jamezpolley** [comment]
@LoveMyData points out to me that lot numbers are not street numbers.

According to the GNAF there's no "10 martin road", so that's definitely not a good number to use.

**Comment by MichaelBone** [comment]
In the end I left the **lot** numbers (and **section** numbers and **hundred** names) out because I thought they'd confuse the geocoding (and after a bit of a look around couldn't find a simple way of translating them into addresses, eg. maybe http://maps.sa.gov.au/plb might provide a way).

I was hoping the street information without the numbers would be enough.

(**Aside**: I think the "hundred" concept is only used in SA and NT.  For example, see https://en.wikipedia.org/wiki/Lands_administrative_divisions_of_South_Australia and https://en.wikipedia.org/wiki/Lands_administrative_divisions_of_Australia.)

**Comment by mlandauer** [comment]
Hi @MichaelBone, please *do* leave the lot, section and hundred names in. They are part of the address, even if normal geocoders on the PlanningAlerts side can't interpret them easily. In the past at least the geocoder that we used was smart enough to just ignore the lot numbers when it can't interpret them but I think it's important for the historical record that the address includes the full information. Thanks!

**Comment by LoveMyData** [comment]
@mlandauer I disagreed a little on this one.

Lot, section, hundreds names (SA, NT) and plan number are identifiers of the land not the address from the legal speak.

Using @jamezpolley example, Lot:10 D: 10840, the street number is 34 Martin Rd

If we are trying to get geocode to work correctly, we should look for alternative like GNAF and other databases should have this information and the lot, section and plan number should be leave _out_ in the address column.

**Comment by LoveMyData** [comment]
however, we can keep historical records and store the land title in a separate columns.

**Comment by MichaelBone** [comment]
@mlandauer, yes, makes sense to keep the information.  Happy to either include it in the address or go with @LoveMyData and add a separate column (which I guess has the advantage of working best with the current geocoder?).  If a separate column then probably best you choose an appropriate name for it (ie. so the same name gets used for any other scrapers).

**Comment by MichaelBone** [comment]
I've changed the scraper to extract the legal description (ie. hundred name, lot number, section number, etc.) into a column named **legal_description** (see #2).

**Comment by MichaelBone** [comment]
Resolved by adding the **legal_description** column (and placing the hundred name, lot number, etc. in that column).
